### ISSUE TITLE
translation of railways

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#269] opened 2021-11-11 14:56 UTC
Hi,

In transifex we have 3 'railway' texts :
railway=railway_crossing
railway=level_crossing
railway=crossing
They are all translate in french.

But in ID, the translations are not visible, we have english words.

Best regards

**Comment by 1ec5** [comment] 2021-11-12 05:27
This is a duplicate of #207.

**Comment by matkoniecz** [comment] 2022-01-06 11:31
@Mahabarata 

Are translations updated like reported in #207 ?

**Closed** 2022-01-07 19:44 UTC
Labels: translations

**Comment by Mahabarata** [comment] 2022-01-08 14:42
No, nothing is working :
- the railway-railway crossing is missing (for tags railway=railway_crossing) : we have still the english version
![Capture d’écran 2022-01-08 113651](https://user-images.githubusercontent.com/3121119/148648326-1affbc9a-6ffb-40fc-a3e3-d25e1f80c6fa.png)
- the railroad-road crossing hasn't the present translation we find in transifex (i.e. "Passage à niveau (route)") but an old one (i.e. "Passage à niveau")
![Capture d’écran 2022-01-08 113730](https://user-images.githubusercontent.com/3121119/148648338-0bd66168-6733-41ac-830a-a9e6d2804a3e.png)
![Capture d’écran 2022-01-08 113838](https://user-images.githubusercontent.com/3121119/148648283-f7c6f3f0-a0ab-444f-a641-60673334c317.png)
- same thing for the railroad path crossing (present translation in transifex = "Passage à niveau (piéton)", present translation in ID = "Passage à niveau" (an old one in transifex).

For me it looks like you have imported in ID an old file from transifex so all the new translations are missing (me and another contributor have created about one thousand of missing translations in french for 2 months and nothing is in ID).

To be more specifix, after my searsh by date in transifex, it looks like all the translations made in transifex since August 2021 are missing.

Is it possible to delete the "closed issue" ?
Best regards

**Comment by Mahabarata** [comment] 2022-01-08 14:57
Another thing :
I think this issue is not the same than the issue #207.

- Here I'm talking of translations in transifex.
- in the other issue, they talk about translations in translatewiki.net : I changed a translation 3 weeks ago in translatewiki and yes, the translation is visible in ID.

Not the translation from transifex.
Best regards

**Comment by Mahabarata** [comment] 2022-01-12 13:41
Hi,

a small test :
here what we have in transifex for Portuguese :
![Capture d’écran 2022-01-12 100314](https://user-images.githubusercontent.com/3121119/149145742-d609fdb1-4e34-4a0b-90df-ac2f65c8d003.png)
Here what we have in ID :
![Capture d’écran 2022-01-12 100344](https://user-images.githubusercontent.com/3121119/149146389-516e2e8a-332b-4fe9-8985-f0df7af0cc01.png)

transifex translations in Portuguese are, like for french, not in ID, for at least 3 months (between August and October, very few translations were made and no translation for objects like node, way, area. But it works for a Portuguese translation made July 19).

I also tried for Russian : translations after August 31 are not in ID.

My first supposition seems the good one : translations from translatewiki.net are ok, not from transifex.

**This issue is clearly not closed**, please change that.
Best regards

**Comment by tordans** [comment] 2022-01-13 10:37
I assume the reasons is, that the id-tagging-schema was not released since "29 Jul 2021". And likely none of the translations there where updated here due to the missing release. 
See https://github.com/openstreetmap/id-tagging-schema/releases
But Martin will know the internals better.
Martin wrote, somewhere, that a new release is planned for the next few weeks.

---

For easy access testing links with `locale=pt`
- dev version https://ideditor.netlify.app/?lang=en#background=Bing&disable_features=boundaries&id=n-1&locale=pt&map=20.00/52.47409/13.44561
- released version https://ideditor-release.netlify.app/#background=Bing&disable_features=boundaries&id=n-1&locale=pt&map=20.00/52.47409/13.44561

**Comment by Mahabarata** [comment] 2022-01-15 15:24
Yes, I agree with that :
but it is not what I'm asking in my last comments : **tyrasd** closed my issue and I'm not agree.

What I ask seems very simple : please open back my issue.
Or tell me you can't if nobody can do that.
Best regards

**Comment by matkoniecz** [comment] 2022-01-15 16:07
It is normal to close issues on tracker once it was fixed in development version, even if released version still have the bug.

**Comment by Mahabarata** [comment] 2022-01-15 22:44
I try both links of tordans, the release and the dev version, with an area with "leisure=indoor_play".
Both are identical : "indoor play center", not "centro de diversoes interior"

This issue is not closed for the release AND not closed for the dev version.

Please open it back.

**Comment by AntMadeira** [comment] 2022-01-15 23:31
@Mahabarata you're right, some recent translations, like the one you mentioned above (`leisure=indoor_play`) that was translated last October, were not updated in iD. I still don't know how this is implemented, but I can guarantee that translations that were stalled for almost a year (like `place=city`, which was changed a loooong ago) were updated on December 11th. That's why I told you on the other topic that they were updated, but as you confirmed, not all of them were updated. Don't ask me why...

**Comment by Mahabarata** [comment] 2022-01-22 13:47
Maybe the end is coming, yay (see #363)
