### ISSUE TITLE
`inscription=*` should not update to `memorial:text=*` on `memorial=stolperstein`

### ISSUE THREAD

**Issue by wielandb** [openstreetmap/id-tagging-schema#1372] opened 2024-11-02 13:22 UTC
Lines to be changed/removed:
https://github.com/openstreetmap/id-tagging-schema/blob/135ad24d0d1b92496d1cf7a6e5a358ea50ccdd7f/data/deprecated.json#L1995C1-L1998C5

There seems to be a consensus that `inscription=` is indeed the correct way to tag what is written on a stolperstein, as every wiki page mentions it like that.

**Comment by tordans** [comment] 2024-11-02 14:18
Quick side note: I am pretty sure is researched this for the initial PR that added the preset. And discussed it it somewhere to find this recommendation.

**Comment by matkoniecz** [comment] 2024-11-02 14:41
> inscription=* should not update to memorial:text=*

maybe I misread linked rule, but it seems to change `"old": {"memorial:text": "*"},` TO `inscription`

**Comment by matkoniecz** [comment] 2024-11-02 14:43
![screen02](https://github.com/user-attachments/assets/8356a2f9-493e-4a17-a4db-d3c055ae276b)

> inscription=* should not update to memorial:text=*

already done, can you close the issue?

**Comment by tordans** [comment] 2024-11-03 04:01
Thanks for taking a look @matkoniecz. I agree that this should be all good and working as intended.

For reference, those are the PR https://github.com/openstreetmap/id-tagging-schema/pull/964 and Issue https://github.com/openstreetmap/id-tagging-schema/issues/318 which holds quite a bit of research on this preset because the tagging was a mess when we started this.

**Closed by tordans** 2024-11-03 04:01 UTC
