### ISSUE TITLE
ID fails to show reference images of crossing types when selecting type of marked crossing in drop downs.  

### ISSUE THREAD

**Issue by ibuddy66** [openstreetmap/id-tagging-schema#1285] opened 2024-07-14 05:04 UTC
**Describe the bug**
When placing a line for a path, selected marked crossing, and then going to crossing markings section, once you enter the drop-down the names of the crossing styles are missing the small reference image that normally populates directly next to each different type of crossing for fast and easy editing reference.   

**To Reproduce**
1. Place a line
2. Chose Marked Crossing for type
3. Scroll down to Crossing Markings
4. Enter the drop-down to find the correct type of markings on the crossing.  Note the empty space next to the words on the left of the crossing marking selections.  A small image of the type of crossing normally shows up here for quick reference and fast editing.  

**Expected behavior**
In the the empty space next to the words on the left of the crossing marking selections.  A small image of the type of crossing normally shows up here for quick reference and fast editing.  

**Screenshots**
![Screenshot 2024-07-14 1 02 53 AM](https://github.com/user-attachments/assets/0419ef56-e415-4df4-8bb9-ff1b122f748d)

**Comment by ibuddy66** [comment] 2024-07-14 05:05
All marking missing except a mislabeled one with nothing but a blank black box showing.

**Comment by tordans** [comment] 2024-07-14 05:32
Thanks for the report, this is a duplicate of https://github.com/openstreetmap/iD/issues/10301 and already fixed but unfortunately still not released.

**Closed by tordans** 2024-07-14 05:32 UTC
Labels: bug
