### ISSUE TITLE
change field site_type to archaeological_site

### ISSUE THREAD

**Issue by b-unicycling** [openstreetmap/id-tagging-schema#720] opened 2022-12-27 22:26 UTC
I've tried this before being a complete newbie to GitHub, and I didn't succeed, so now I brought a picture to make myself understood.
![site_type field](https://i.imgur.com/xP0rnscl.png)
Can you **please** change the form for archaeological sites, so that both the form **and the key** say "`archaeological_site`" rather than "`site_type`", because `site_type` is deprecated.

There are now new sites being mapped with "site_type", because it hasn't been changed yet.

**Comment by arch0345** [comment] 2022-12-28 04:41
Duplicate of #677

This issue was fixed in https://github.com/openstreetmap/id-tagging-schema/commit/f2eef8e72b14e96a90388bfd29716db928b3bd6a, however this change won't appear in iD until the next release is published (the fix linked was from 2 weeks ago while the [latest release](https://github.com/openstreetmap/id-tagging-schema/releases/tag/v5.1.1) was published 3 weeks ago)

**Comment by tordans** [comment] 2022-12-29 13:37
> There are now new sites being mapped with "site_type", because it hasn't been changed yet.

Just to add to this: This will always be the case with OSM. Whenever we change tags we have to prepare to cleanup for at least a year or even longer until the old data is out of the "system" (tools, qa-tools, "heads"). For the update of parking-tagging we build a tag update helper and plan to create MapRoulette Challenges per Country to "accompany" the update process.

**Closed** 2023-01-10 13:10 UTC
Labels: duplicate
