### ISSUE TITLE
Bug highway=service/service=

### ISSUE THREAD

**Issue by DiogoBaptista98** [openstreetmap/id-tagging-schema#643] opened 2022-11-15 19:24 UTC
https://github.com/openstreetmap/iD/issues/9376

DELETE

**Comment by waldyrious** [comment] 2022-11-16 10:57
@DiogoBaptista98 if this is a duplicate of https://github.com/openstreetmap/iD/issues/9376, why don't you simply close the issue?

**Closed** 2022-11-17 18:30 UTC
Labels: bug, duplicate
