### ISSUE TITLE
Wikipedia language selection in multilingual countries

### ISSUE THREAD

**Issue by bxl-forever** [openstreetmap/id-tagging-schema#405] opened 2022-02-19 11:47 UTC
iD offers to upgrade the tags of objects.  For instance, adding operator:wikidata and operator:wikipedia for some recognized brands.

Consider the following case.  Belgium is a country with 3 official languages: Dutch (nl), French (fr) and German (de).  Each language has its own territory, though we have the same brands.
operator=bpost
operator:wikidata=Q740553
operator:wikipedia=XX:Bpost

XX could be anything among the 3 languages.
If the German article is available iD will always take this one.  This goes against the principle of least surprise because this is by far the least-spoken language in our country.
And if mappers change the tag into their local language, iD will encourage other mappers to restore the German article.

Here is the feature request:
1) Establish a priority order for languages in multilingual countries (for Belgium, it would be "nl", "fr", "de")
2) If a *:wikipedia entry already exists, do not offer to change it.

**Comment by tyrasd** [comment] 2022-02-20 11:43
> If the German article is available iD will always take this one.

Can you please explain how exactly you got this behavior? When I'm trying to reproduce the issue, I see the following behavior: If I add `Q740553` in the wikidata field, and have iD running in English, the English wikipedia article is linked as `wikipedia=en:Bpost`. However, when I have open iD with the Dutch locale, `wikipedia=nl:Bpost` is used.

**Comment by bxl-forever** [comment] 2022-02-20 12:48
I tried to reproduce the problem, here are some details.
Apparently, when using  `wikidata=Q740553`, iD will correctly add `wikipedia=en:Bpost`.
On the other hand, when using wikidata as a suffix, like in `operator:wikidata`, it will surprisingly use `de:Bpost`.
My locale in en_US.

**Comment by tyrasd** [comment] 2022-02-22 08:46
Maybe I'm overlooking something obvious, but how exactly do you get iD to automatically add a `operator:wikipedia` tag after adding a `operator:wikidata` tag? I thought that only the `"type": "wikidata"` UI fields automatically also sync the respective wikidata and wikipedia fields, but there is no field for `operator:wikdata` as far as I can see in the presets database. When I manually add the `operator:wikidata=Q740553` tag in the tags editor directly, no `operator:wikipedia` tag is added at all.

**Comment by 1ec5** [comment] 2022-02-22 09:35
> iD offers to upgrade the tags of objects. For instance, adding operator:wikidata and operator:wikipedia for some recognized brands.

The `operator:wikidata` tag is [coming from name-suggestion-index](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&tt=bpost#bpost-1b232e). It’s possible to replace [the current bpost entry](https://github.com/osmlab/name-suggestion-index/blob/5d0934080ca3f59d58c2c270bcc240ed3e8f85e9/data/operators/amenity/post_office.json#L143-L153) with three entries, one for each language with a different Wikipedia tag and a different `locationSet` that’s more specific than `be`.

There have been many requests for NSI to drop its `*:wikipedia` tags entirely, partly because they’re redundant to both `name` and `wikidata`, but also because people often don’t expect foreign languages to show up on features halfway across the world: [osmlab/name-suggestion-index#6012](https://github.com/osmlab/name-suggestion-index/pull/6012#pullrequestreview-845120476). In the meantime, you can create separate regional entries or change the Wikipedia link on the existing one to be a more common language.

**Comment by tyrasd** [comment] 2022-02-22 09:53
Aaah, I totally overlooked that first sentence. Sorry for that.

I'll close the issue here since it's not an issue with iD itself or the regular iD presets.

**Closed by tyrasd** 2022-02-22 09:53 UTC
